spring.application.name = springsteps

spring.datasource.url = jdbc:h2:file:~/springsteps
spring.datasource.username = admin
spring.datasource.password = geheim

# Automatische Erzeugung von Tabellen
spring.jpa.hibernate.ddl-auto = update

# SQL wird auf der Konsole angezeigt
spring.jpa.show-sql = false

# H2 Web-Client wird eingeschaltet
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console